---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/roles

platforms:
  - name: ubuntu-12.04

suites:
  - name: vpn
    run_list:
      - recipe[apt]
      - role[openvpn]
  - name: oob
    run_list:
      - recipe[apt]
      - role[oob-vpn]
